apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shetty143/backend-image:v6  # ← replace with your image
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: backend-db.cz2g44isob5v.ap-south-2.rds.amazonaws.com      # ← replace with actual RDS host
        - name: DB_NAME
          value: postgres                                # ← or your custom DB name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: password
