apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: test
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Pick a NodePort between 30000–32767

